#!/bin/bash
# checks root and if not exits

if [[ -f /usr/bin/checkroot ]]; then
:
else
ln -s $(pwd)/checkroot /usr/bin/checkroot
fi

if [[ $(id -u) -gt "0" ]]; then
echo This program needs to run as root!
exit 1
else
:
fi

