#!/bin/bash
# This program will symlink the individual modules so they can be run seperately from the command line
echo This program will symlink the modules.
echo Continue? \[Y\/N\]
read confirm
case $confirm in
Y|y)
ln -s $(pwd)/modules/complete-destroy-pkg /usr/bin/complete-destroy-pkg
echo Symlinked complete-destroy-pkg.
ln -s $(pwd)/modules/diskchecker /usr/bin/diskchecker
echo Symlinked diskchecker
ln -s $(pwd)/modules/makeservice /usr/bin/makeservice
echo Symlinked makeservice
ln -s $(pwd)/modules/viewcron /usr/bin/viewcron
echo Symlinked viewcron
echo
echo Done!
exit 0
;;
*)
exit 1
;;
esac
