#!/bin/bash
# This program will symlink the individual modules so they can be run seperately from the command line

# First let's check the privileges.

if [[ $(id -u) -gt "0" ]]; then
 echo This program probably should be run as root.
 exit 1
else
 :
fi

function installmod() {
 if [ -e /usr/bin/$1 ]; then
  echo $1 already exists, skipping...
 else
  ln -s $(pwd)/modules/$1 /usr/bin/$1
  echo $1 has been installed.
 fi
}

echo This program will symlink the modules.
echo Continue? \[Y\/N\]
 read confirm
 case $confirm in
  Y|y)
   echo
   echo Enabling global "checkroot" alias...
   if grep checkroot /etc/bash.bashrc >/dev/null; then
   echo Checkroot already present, skipping...
   else
   printf "alias checkroot='if [[ $(id -u) -gt 0 ]] ; then echo Please run as root ; exit 1 ; fi'" >>/etc/bash.bashrc && source /etc/bash.bashrc
   echo Enabled checkroot alias
   fi
   installmod complete-destroy-pkg
   installmod diskchecker
   installmod makeservice
   installmod viewcron
   installmod checkcert
   echo
   echo Done symlinking stuff.
  exit 0
  ;;
 *)
  exit 1
  ;;
 esac


# Test
